### ISSUE TITLE
Need explanation of what case_col column is from column_metadata table

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/etl_flow#110]

**Comment by G-White-ISB** [comment]
This is mentioned in the clinical data documentation: https://learn.canceridc.dev/data/organization-of-data/clinical

case_col is a Boolean which is true if and only if the referenced column contains the patient or case id, i.e. if this column is used to determine the value of the dicom_patient_id column

**Comment by fedorov** [comment]
thank you - I did look at that page, but missed it
