### ISSUE TITLE
Replace `tcia_` prefix

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/etl_flow#49]
Since we no longer receive data just from TCIA, the prefix `tcia_` is misleading in `dicom_all`:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/313942/213544433-e782a622-91fe-42ce-b22c-96cdd1a469da.png">

Per discussion, agreed to introduce new columns duplicating the originally named ones, but using `collection_` in place of `tcia_` prefix. In the tutorial materials, we will phase out the use of `tcia_` prefixes.

These attributes come from https://console.cloud.google.com/bigquery?project=idc-tcia&p=bigquery-public-data&d=idc_current&t=dicom_all&page=table&ws=!1m20!1m4!4m3!1sidc-sandbox-000!2spathomics!3sadd_pathomics_attrs!1m4!1m3!1sidc-tcia!2sbquxjob_5e722d0f_185cb6f5d9c!3sUS!1m4!4m3!1sidc-dev-etl!2sidc_v13_pub!3soriginal_collections_metadata!1m4!1m3!1sidc-tcia!2sbquxjob_4c786b88_185cb711265!3sUS, and so they already contribute to collection-level metadata, so the name is logical.

**Comment by bcli4d** [comment]
Added duplicate columns named collection_tumorLocation, etc.
